version: '3'

name: e2esdk-dev

services:
  db:
    image: postgres:14.1
    ports:
      - '3002:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=e2esdk
    volumes:
      - .volumes/docker/$COMPOSE_PROJECT_NAME/db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      start_period: 3s
      retries: 50
