version: '3'

services:
  db-sdk:
    image: postgres:14.1
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=e2esdk
    volumes:
      - .volumes/storage/e2esdk/db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      start_period: 3s
      retries: 50
