version: '3'

name: e2esdk-examples-contact-forms

services:
  # Application layer --

  app-db:
    image: postgres:14.1
    ports:
      - '4001:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - ../../../.volumes/docker/$COMPOSE_PROJECT_NAME/app-db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      start_period: 3s
      retries: 50

  app-hasura:
    build: ./src/hasura
    env_file: ./src/hasura/.env
    restart: unless-stopped
    ports:
      - '4002:8080'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      app-db:
        condition: service_healthy

  # E2ESDK --

  e2esdk-db:
    image: postgres:14.1
    ports:
      - '4004:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=e2esdk
    volumes:
      - ../../../.volumes/docker/$COMPOSE_PROJECT_NAME/e2esdk-db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      start_period: 3s
      retries: 50

  e2esdk-db-verify-image-signature:
    image: ghcr.io/socialgouv/e2esdk/server:beta
    command: packages/server/node_modules/.bin/sceau verify --packageDir packages/server --strict

  e2esdk-db-ops:
    image: ghcr.io/socialgouv/e2esdk/server:beta
    #build:
    #  context: ../../../
    #  dockerfile: ./packages/server/Dockerfile
    environment:
      - POSTGRESQL_URL=postgres://postgres:password@e2esdk-db:5432/e2esdk
    command: pnpm db migrations apply
    links:
      - e2esdk-db
    depends_on:
      e2esdk-db:
        condition: service_healthy

  e2esdk-server:
    image: ghcr.io/socialgouv/e2esdk/server:beta
    # build:
    #   context: ../../../
    #   dockerfile: ./packages/server/Dockerfile
    ports:
      - '4003:3000'
    environment:
      - DEPLOYMENT_URL=http://localhost:4003
      - POSTGRESQL_URL=postgres://postgres:password@e2esdk-db:5432/e2esdk
      - SIGNATURE_PUBLIC_KEY=gsE7B63ETtNDIzAwXEp3X1Hv12WCKGH6h7brV3U9NKE
      - SIGNATURE_PRIVATE_KEY=___examples-server-signkey__NOT-FOR-PROD__yCwTsHrcRO00MjMDBcSndfUe_XZYIoYfqHtutXdT00oQ
      - CORS_ALLOWED_ORIGINS=http://localhost:4000
      - RELEASE_TAG=local
    links:
      - e2esdk-db
    depends_on:
      app-db:
        condition: service_healthy
      e2esdk-db-verify-image-signature:
        condition: service_completed_successfully
      e2esdk-db-ops:
        condition: service_completed_successfully


