name: CI
on:
  - push
  - pull_request

env:
  HUSKY: 0
  FORCE_COLOR: 3

jobs:
  tag:
    name: Release Tag
    runs-on: ubuntu-latest
    steps:
      - name: Generate release tag
        id: release-tag
        run: echo "tag=${{ github.ref_name }}@$(date +%Y-%m-%d_%H.%M.%S)_$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Display release tag
        run: echo "::notice title=Release Tag::${{ steps.release-tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.release-tag.outputs.tag }}

  ci:
    name: Integration
    runs-on: ubuntu-latest
    needs: tag
    env:
      RELEASE_TAG: ${{ needs.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.sha }}

      - name: Install dependencies
        run: pnpm install

      - name: Configure env
        run: cp ./packages/server/.env.example ./packages/server/.env

      - name: Lint
        run: pnpm lint

      - name: Unit tests
        run: pnpm test

      - name: Type checking
        run: pnpm typecheck

      # - name: Send test coverage to codecov
      #   continue-on-error: true
      #   uses: codecov/codecov-action@v2

      - name: Build (NPM)
        run: pnpm build:npm

      - name: Build (Docker)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: packages/server/Dockerfile
          build-args: |
            RELEASE_TAG=${{ env.RELEASE_TAG }}
          tags: |
            e2esdk/server:ci
            e2esdk/server:${{ env.RELEASE_TAG }}
          push: false

      # - name: Functional tests
      #   run: pnpm e2e

      # - name: Build to lib folder for archives
      #   run: pnpm build --outDir lib

      # - name: Archive lib components
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: components
      #     path: lib/
